version: '3.9'

services:
    database:
        image: postgres
        container_name: teste
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: "123"
            POSTGRES_DB: Projeto
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local
